application:
  name: "twitchtestbot"
  project: "twitchTestBot"
  organization: "QoveryCommunity"
  dockerfile: "src/twitchbot/Dockerfile"
  depends_on:
    - "my-mongodb"
databases:
  - type: "MONGODB"
    version: 4.4
    name: "my-mongodb"
routers:
  - name: "main-twitchtestbot"
    routes:
      - application_name: "twitchtestbot"
        paths:
          - "/*"
